### PR TITLE
fix: createURI() should not persist uri

### LINKED ISSUE #1489: Ever increasing json file when creating resumable upload urls
#### Environment details

  - OS: Linux
  - Node.js version: 10
  - npm version:
  - `@google-cloud/storage` version:  5.8.5

#### Steps to reproduce

  1. create a resumable upload url by using `createResumableUpload()`
  2. look at file `.config/configstore/gcs-resumable-upload.json`

When creating a resumable upload urls the package seems to write that to a json file that is ever increasing and never cleaned up.
This makes calls to `createResumableUpload` slower over time because that json is parsed on each call.
Another side effect are high volume of disk writes.

Not sure if this is an issue with this package or with `gcs-resumable-upload` because this lib is using a [method from there](https://github.com/googleapis/nodejs-storage/blob/390469a2283fd85ee3e1121d77505e77e16dbf10/src/file.ts#L1549).
The file seems to be the one sent as `configPath`.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes https://github.com/googleapis/nodejs-storage/issues/1489

When a user uploads a file, we internally call "createURI()" to generate the resumable upload URI. We realized later that users might just need the URI, but not want to upload a file with this library. So, we exposed the function publicly.

We left behind an internal implementation detail, though, which had a side effect. We use `ConfigStore` to persist the URI, so that during an interrupted upload, we can pick up where we left off with the data we cached. As https://github.com/googleapis/nodejs-storage/issues/1489 points out, that's not something they need, and it's been using up disk space.

To fix the issue, we will only persist the URI during a deliberate upload attempt. Otherwise, we will simply return the URI.

### CODE REVIEW

File: test/test.ts [hunk 1]
```diff
@@ -322,6 +322,18 @@ describe('gcs-resumable-upload', () => {
         };
         up.emit('writing');
       });
+
+      it('should save the uri to config', done => {
```
Comment (shaffeeullah) [inline test/test.ts:326]: @stephenplusplus what is the difference between this test and the test below? Are there tests for both cases (case where uri should be saved and case where uri should not be saved)? I might be missing something

**Review by shaffeeullah — COMMENTED** [review]
Thanks for this implementation, @stephenplusplus !!

File: test/test.ts (hunk 1 above)
Comment (stephenplusplus) [reply test/test.ts:326]: That's funny, I didn't realize I could have copy/pasted the whole thing 😆 The only thing that's changing in the tests is what triggers the call to `createURI()`.

`createURI()` won't call `set()` anymore, so I removed the test that used to confirm we called it. In these new tests, we're checking that where we call `createURI()` internally, we also call `set()` right after with the result.

Comment (shaffeeullah) [reply test/test.ts:326]: ah, makes sense!!

**Review by shaffeeullah — APPROVED** [review]

**Review by shaffeeullah — CHANGES_REQUESTED** [review]
Can you please change the test descriptions so they don't have the same title? Otherwise, looks good!

**Comment by stephenplusplus** [comment]
> Can you please change the test descriptions so they don't have the same title? Otherwise, looks good!

Done!

**Review by shaffeeullah — APPROVED** [review]
Thanks for doing this stephen! Lint check is failing, but other than that it looks good!

**Comment by stephenplusplus** [comment]
Woops, fixed! Thanks for the review!
